import { ProductTypes } from '../../generated/types';

export const DEPRECATED_PRODUCT_TYPE: Record<ProductTypes, boolean> = {
  [ProductTypes.singleProtocol]: false,
  [ProductTypes.theRetailMutual]: false,
  [ProductTypes.multiProtocol]: false,
  [ProductTypes.nativeProtocol]: false,
  [ProductTypes.ethSlashingUmbrella]: false,
  [ProductTypes.openCoverTransaction]: false,
  [ProductTypes.fundPortfolio]: false,
  [ProductTypes.sherlockBugBounty]: false,
  [ProductTypes.deFiPass]: false,
  [ProductTypes.immunefiBugBounty]: false,
  [ProductTypes.nexusMutual]: false,
  [ProductTypes.generalizedFundPortfolio]: false,
  [ProductTypes.crypto]: false,
  [ProductTypes.nativeSyndicate]: false,
  [ProductTypes.spearbitCantina]: false,
  [ProductTypes.leveragedLiquidation]: false,
  // Deprecated product types
  [ProductTypes.ethSlashing]: true,
  [ProductTypes.liquidCollectiveEthStaking]: true,
  [ProductTypes.stakewiseEthStaking]: true,
  [ProductTypes.sherlockQuotaShare]: true,
  [ProductTypes.unoReQuotaShare]: true,
  [ProductTypes.custody]: true,
  [ProductTypes.yieldToken]: true,
  [ProductTypes.sherlockExcess]: true,
  [ProductTypes.followOn]: true,
};

export const PRIVATE_PRODUCT_TYPE: Record<ProductTypes, boolean> = {
  [ProductTypes.singleProtocol]: false,
  [ProductTypes.multiProtocol]: false,
  [ProductTypes.custody]: false,
  [ProductTypes.yieldToken]: false,
  [ProductTypes.nexusMutual]: false,
  [ProductTypes.crypto]: false,
  // Private product types
  [ProductTypes.ethSlashing]: true,
  [ProductTypes.liquidCollectiveEthStaking]: true,
  [ProductTypes.stakewiseEthStaking]: true,
  [ProductTypes.sherlockQuotaShare]: true,
  [ProductTypes.unoReQuotaShare]: true,
  [ProductTypes.theRetailMutual]: true,
  [ProductTypes.sherlockExcess]: true,
  [ProductTypes.nativeProtocol]: true,
  [ProductTypes.ethSlashingUmbrella]: true,
  [ProductTypes.openCoverTransaction]: true,
  [ProductTypes.fundPortfolio]: true,
  [ProductTypes.sherlockBugBounty]: true,
  [ProductTypes.deFiPass]: true,
  [ProductTypes.followOn]: true,
  [ProductTypes.immunefiBugBounty]: true,
  [ProductTypes.generalizedFundPortfolio]: true,
  [ProductTypes.nativeSyndicate]: true,
  [ProductTypes.spearbitCantina]: true,
  [ProductTypes.leveragedLiquidation]: true,
};
