name: pull-request
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22
  PROVIDER_URL: https://eth-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}

jobs:
  version:
    runs-on: ubuntu-22.04
    if: github.base_ref == 'master'
    outputs:
      local_version: ${{ steps.local_version.outputs.value }}
      registry_version: ${{ steps.registry_version.outputs.value }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Validate potential version bump
        id: validate_version_bump
        run: |
          # Check if conventional commits would trigger a version bump
          BUMP=$(timeout 5s npx conventional-recommended-bump --config .github/config/conventional-bump-setup.js) || true
          
          echo "Conventional commit analysis result: $BUMP"
          
          if [[ "$BUMP" == *"No version bump needed"* ]]; then
            echo "::error::Forbidden to release a version without a version bump"
            echo "::warning::Commit messages must include changes beyond 'docs', 'style', 'test', or 'ci'"
            echo "Please ensure your commits reflect meaningful changes to trigger an automatic version bump."
            exit 1
          fi

  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts --prefer-offline --no-audit --no-fund

      - name: Build package
        run: npm run build

      - name: Run linter
        run: npm run lint

      - name: Run prettier
        run: npm run format

      - name: Check types and typescript
        run: npm run ts:check

      - name: Run tests
        run: npm run test
