name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22
  PROVIDER_URL: ${{ secrets.PROVIDER_URL }}

jobs:
  checks:
    # Skip CI for draft PRs since this workflow is triggered once its review for review
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Run build script to generate `/generated` dir which is needed by ts:check and test scripts
      - name: TypeScript build
        run: pnpm run ts:build

      - name: Run linter
        run: pnpm run lint

      - name: Check types and typescript
        run: pnpm run ts:check

      - name: Run tests
        run: pnpm run test
